tmux new-window -n "io" "/usr/bin/iostat -dktx 2"
tmux split-window -h "/usr/bin/iostat -dktx 3600"
tmux new-window -n "cpu" "/usr/bin/sar 2"
tmux split-window -h "/usr/bin/sar 3600"
tmux new-window -n "net" "/usr/bin/sar -n DEV 2"
tmux split-window -h "/usr/bin/sar -n DEV 3600"
